cask/cask

README.md
- Use new domain
- Remove -k(--insecure) option
=> Fix download command same as 'doc/guide/installation.rst'

cask.el
This is related to #311.
```
% cask
Package lacks a file header in file /home/syohei/.cask/cask-cli.el
```
```
% cask
Package lacks a footer line in file /home/syohei/.cask/cask-cli.el
```
```
% cask
Package lacks a "Version" or "Package-Version" header in file /home/syohei/.cask/cask-cli.el
```
```
% cask
Invalid version syntax: ‘1.8..1’ in file /home/syohei/.cask/cask-cli.el
```
=> Improve package error message

bin/cask, doc/guide/usage.rst
=> Add support for CASK_EMACS environment variable.

features/exec.feature
=> Update test to reflect improved error message

bin/cask, features/emacs.feature
Fix Broken logic in the command line handling, add ecukes test.
What could go wrong? Well, in the last tweaks to my PR, it appears I copied one fix wrong, did not check it was working, and had no tests to pick the issue up either.
10 out of 10 for style, minus several million for good thinking.
=> Fix emacs command

cask.el
=> convert package-name to string

cask-bootstrap.el, cask-cli.el, cask.el
Related to #428 
https://asciinema.org/a/zKc2P9DOFyf2JknDTpA98noMN
We can make it a bit less stupid, this is a POC implementation.
=> Log the install progress

cask.el, doc/guide/dsl.rst
refs https://github.com/sunrise-commander/sunrise-commander/issues/57, https://github.com/sunrise-commander/sunrise-commander/issues/72
=> SC (Sunrise Commander) repository which no longer exists

cask.el
=> bump v0.8.5

cask.el
Hi!
I want to contribute by this fixing small issues as a first
contribution step!
=> Fix package-lint/byte-compiler/check-doc warnings

doc/dev/contributing.rst, docker/.gitignore, docker/Dockerfile-24.1, docker/Dockerfile-24.2, docker/Dockerfile-24.3, docker/Dockerfile-24.4, docker/Dockerfile-24.5, docker/Dockerfile-25.1, docker/Dockerfile-25.2, docker/Dockerfile-25.3, docker/Dockerfile-26.1, docker/Dockerfile-26.2, docker/Dockerfile-26.3, docker/Dockerfile-27.1, docker/Dockerfile.mustache, docker/generate-dockerfile
Add Dockerfile for clean testing environment.
=> Add Dockerfile for clean testing environment

README.md, go
Add deprecation warning on `go` script.
=> Add deprecation warning on `go` script

README.md
Fix trivial; change description command
=> Fix trivial; change description command

doc/dev/contributing.rst
Add doc/contributing misc section
=> Add doc/contributing misc section

doc/dev/contributing.rst, docker/Dockerfile-24.1, docker/Dockerfile-24.2, docker/Dockerfile-24.3, docker/Dockerfile-24.4, docker/Dockerfile-24.5, docker/Dockerfile-25.1, docker/Dockerfile-25.2, docker/Dockerfile-25.3, docker/Dockerfile-26.1, docker/Dockerfile-26.2, docker/Dockerfile-27.1, docker/Dockerfile-master, docker/Dockerfile.mustache, docker/generate-dockerfile
Add Docker image for HEAD Emacs
=> Add Docker image for HEAD Emacs

doc/conf.py, go
=> Apply black formatter

bin/cask
Fill paragraph on Python document
=> Fill paragraph on Python document

docker/Dockerfile-24.1, docker/Dockerfile-24.2, docker/Dockerfile-24.3, docker/Dockerfile-24.4, docker/Dockerfile-24.5, docker/Dockerfile-25.1, docker/Dockerfile-25.2, docker/Dockerfile-25.3, docker/Dockerfile-26.1, docker/Dockerfile-26.2, docker/Dockerfile-26.3, docker/Dockerfile-27.1, docker/Dockerfile-master, docker/Dockerfile.mustache
Create symbolic link with force option
=> Create symbolic link with force option

cask-bootstrap.el, cask-cli.el, cask.el
=> Work again on Emacs-24.5

cask-bootstrap.el
defvar tls-program to suppress warning
=> defvar tls-program to suppress warning

cask-bootstrap.el
tls hack Emacs-24.5 too to simplify condition
=> tls hack Emacs-24.5 too to simplify condition

cask-bootstrap.el
Merge old emacs hack condition
=> Merge old emacs hack condition

features/step-definitions/cask-steps.el
Temporary comment out fail test
=> Temporary comment out fail test

features/exec.feature, features/step-definitions/cask-steps.el
Re: Temporary comment out fail test
=> Re: Temporary comment out fail test

cask-bootstrap.el
=> restore load-path using let

cask-bootstrap.el
=> Refactor cask-bootsrap

cask-bootstrap.el, cask-cli.el, cask.el, features/support/env.el, test/cask-api-test.el, test/test-helper.el
=> Remove dash dependency

cask.el
=> Fix byte-compiler warning

bin/cask.bat
…that was outdated after migrating to Bash from Python.
=> Update a comment in cask.bat

cask-cli.el
Show deprecation notice if user run cask with Emacs <= 24.4
https://github.com/cask/cask/issues/523#issuecomment-809378637
=> Show deprecation notice if user run cask with Emacs <= 24.4

.github/workflows/test.yml
I think this is cleaner than putting `if` clause in every step. See [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations) on the syntax.
=> Clean up the CI configuration using matrix.include

README.org
=> CI badge display on master

bin/cask
Resolves https://github.com/cask/cask/pull/561#discussion_r829034554
=> Try both readline and greadlink

.github/workflows/test.yml
=> tests(test.yml): Add test for Emacs 28.2
