cask/cask

cask.el
I propose this change to make Cask work well when installed with a package manager (i.e. not having write access to the installation directory). Using the real temp directory has other advantages and I couldn't find a reason not to use it by default.
=> Use the systems temporary file directory

Cask, cask-cli.el, doc/guide/usage.rst, features/eval.feature, features/step-definitions/cask-steps.el
I added this command so I could check which Emacs version was running, but it seems that it might be more generically useful. Will patch up the documentation iff you think its worth while.
This allows executing arbitrary lisp in the context of the current
project.
=> Adds support for eval command.

bin/cask
Fixes a typo.
Use
`EMACSLOADPATH`
instead of
`EMACSLISPPATH`
=> Fix docstring for 'cask exec'

doc/guide/usage.rst
The cask.el file is found in `/usr/local/share/emacs/site-lisp/cask/cask.el`
and not `/usr/local/share/emacs/site-lisp/cask.el`. The directory `cask`
is missing in the path.
=> Update usage docs for Homebrew installation

cask-bootstrap.el, cask-cli.el, cask.el, doc/guide/dsl.rst, package-legacy.el, test/cask-api-test.el
HTTP sends plaintext messages, so it leaks information and is vulnerable to MITM attacks. ELPA, MELPA, and Marmalade all support HTTPS. We should make use of it.
This changes the default addresses for those sources to use HTTPS. Users that have built Emacs to handle TLS will be able to make use of these sources, and Emacs will fall back to using regular HTTP if it isn't configured to handle TLS.
This also updates the documentation to point to the HTTPS address of those repositories.
This should close https://github.com/cask/cask/issues/323.
=> Use HTTPS to connect to sources that support it

bin/cask, doc/guide/usage.rst
Partly this saves a bit of typing (i.e. `cask emacs` rather than `cask exec emacs`), but mostly because it ensures that the same Emacs is run as would normally be the case.
=> Add an Emacs command, to run Emacs directly.

doc/guide/usage.rst
Mention that dependencies will have to be installed for each version of Emacs used.
See #339.
=> Note that dependencies are scoped on version

cask.el, features/step-definitions/cask-steps.el, test/cask-api-test.el
Previously cask creates a new directory for every version string change,
which, for those running from a development build means most rebuilds.
Now, just use the emacs major and minor version.
=> Simplify the cask install directory.

bin/cask
75b6148 explicitly use byte-string environment variables in python 3,
and fails when tries to compare it with plain strings. 
```shell
~ $ INSIDE_EMACS=t python3 -c "import os; print(os.environb[b'INSIDE_EMACS'] == 't')"
False
~ $ INSIDE_EMACS=t python3 -c "import os; print(os.environb[b'INSIDE_EMACS'] == b't')"
True
~ $ INSIDE_EMACS=t python2 -c "import os; print(os.environ[b'INSIDE_EMACS'] == 't')"
True
~ $ INSIDE_EMACS=t python2 -c "import os; print(os.environ[b'INSIDE_EMACS'] == b't')"
True
```
=> Use byte-strings to compare environment variables

cask.el
`package-build.el` behaves incorrectly with relative paths.
=> Expand cask package target-dir

cask-cli.el
Currently `cask help` does not show document of `emacs` subcommand.
=> Define emacs subcommand for 'cask help'

cask-bootstrap.el, cask.el
Should have done this with the last commit, but hadn't realised that the full version string was used here also.
=> Simplify the cask bootstrap directory.

cask.el, test/cask-api-test.el
The f-same? function changed and required the files to exist to be same, but that might not be the case here. Use string equality check instead.
=> Check equality using string comparison

bin/cask
This is related to #374 issue.
=> Show help by 'cask exec'(no command arguments)

bin/cask, features/exec.feature, features/step-definitions/cask-steps.el, features/support/env.el
This is a workaround for a bug in pyenv which is affecting Travis
builds. pyenv is currently adding `/usr/bin` to the front of $PATH for
anything run through python. This screws up emacs version management
with evm which relies on the evm bin directory being earlier in the path
than any other directory containing emacs binaries.
Fixes #399.
=> If /usr/bin is at the front of $PATH, strip it

bin/cask, features/exec.feature, features/step-definitions/cask-steps.el, features/support/env.el
Reverts cask/cask#400
The fix doesn't seem to work in some cases, I'm not yet sure why.
=> Revert "If /usr/bin is at the front of $PATH, strip it"

bin/cask, features/exec.feature, features/step-definitions/cask-steps.el, features/support/env.el
This is a second attempt at fixing this issue, the first one didn't work in some cases so I rolled it back. This time I managed to test my changes on Travis (by messing with the bootstrap process), and it does pick the correct emacs version as you can see [here](https://travis-ci.org/davidshepherd7/electric-operator/jobs/288197732).
The only thing I've changed from the previous attempt is that the PATH modifications are now in `main` instead of only in `exec_command` (which isn't always used). So now the path is fixed in everything that cask does instead of only when using `cask exec ...` or `cask emacs ...`.
---------------------------------------------------------------------------------------------------------
This is a workaround for a bug in pyenv which is affecting Travis
builds. …
=> If /usr/bin is at the front of $PATH, strip it -- attempt 2

cask.el, templates/init-dev.tpl, test/cask-api-test.el
If we're in a directory that only contains a single foo.el, that's
probably the value we want for package-file.
Before:
(package-file "TODO")
After:
(package-file "foo.el")
If it's ambiguous, use the previous behaviour.
=> cask init: autofill the package-file value

cask-bootstrap.el, cask.el
- Adjust cask-package to use package-recipe.
- Use package-recipe when interacting with package-build--checkout
Fixes #421
=> Adjust cask to new package-build APIs

cask-bootstrap.el, cask.el, doc/guide/dsl.rst, features/package-descriptor.feature
Sometimes you want to just explicitly enumerate package metadata yourself in a `-pkg.el` that contains everything from the name, to the dependencies.
This allows Cask to read package metadata from a pre-existing package descriptor by adding the `package-descriptor` directive. This directive functions in a very similar fashion to the `package-file` directive. For example, if you have a package descriptor in `my-package-pkg.el"`, that looks like:
```elisp
(define-package "my-package" "1.0.0" "a great package"
'((foo "2.8.0")
(bar "0.7.0")
(bazz "0.13.0"))
:keywords '("awesome" "possum"))
```
You can have Cask use it by including this line in your `Cask` file.
```elisp
(package-descriptor "my-package-pkg.el")
````
resolves #381
=> add package-descriptor directive

cask-cli.el, doc/dev/contributing.rst, doc/guide/dsl.rst, doc/guide/usage.rst
Just fixed a few typos I noticed when using `Cask`.
=> Fix a few typos

doc/guide/usage.rst
Previously the documentation did not state that term-mode is still
effected in later Emacs versions.
Closes #371
=> Update doc describing use of CASK_EMACS

cask.el
This fixes issue #426.
`package-build-package` was renamed to private `package-build--package`.
Using the private function was recommended in https://github.com/melpa/package-build/issues/20 as a quick fix and to work with them to create a reasonable public API that cask can use.
Thanks
=> Use private package-build--package

cask.el, test/cask-api-test.el
Fixes #432
It is sometimes convenient to create executable scripts in the package to do routine tasks.  It is often useful to run these inside the proper environment that `cask exec` provides.
This patch adds all the directories from `cask files` which contain executable files to the `exec-path`.
=> Add package executable files to exec-path

cask.el
When a package is anavailable the log used to look like this:
Loading package information... done
Package operations: 5 installs, 0 removals
- Installing [ 1/5] mmm-mode (0.5.4)...   - Installing [ 2/5] cl-lib (0.5)... already present
- Installing [ 3/5] emacs (24.3)... already present
Now it looks like this:
Loading package information... done
Package operations: 5 installs, 0 removals
- Installing [ 1/5] mmm-mode (0.5.4)... not available
- Installing [ 2/5] cl-lib (0.5)... already present
- Installing [ 3/5] emacs (24.3)... already present
=> Indicate unavailable packages in install log

cask.el
The shutup macro was removed in
4e91656e4e0ac92a7d43e83ac113a76c4347bc10 but the use of
shut-up-current-output was left although it's not valid outside of the
macro.
=> Remove stray shutup expression

doc/guide/installation.rst
Added `~/.cask` to the end of the git command so that the subsequent instructions for modifying the PATH environment also works for git cloning.
=> Add ~/.cask to git command

cask-bootstrap.el
In emacs 27/28, the function `package-initialize` will be called by emacs automatically.
=> Avoid twice call to ‘package-initialize’ in emacs 27/28

cask-bootstrap.el
This opens a path to vendoring bootstrap packages: they will not be installed
properly, but they will be requirable with some path extensions.
Pre-requisite to #492
=> Check and install bootstrap packages one by one

cask-bootstrap.el, package-build-legacy.el, package-recipe-legacy.el
This PR adds vendoring for earlier versions of `package-build` package that is compatible with Emacs 24.
=> Vendor older versions package-build & package-recipe for Emacs 24.*

bin/cask
Possibly a duplicate of https://github.com/cask/cask/pull/449; I coded it up and tested it before checking open pulls (though that PR is few years old).
This PR shims environ to decode bytes strings or convert other params to strings for Windows.  Tested on Windows/Linux with python 2 and 3.
=> Add shim to workaround environb missing on Windows.

cask-bootstrap.el
This should fix couple of remaining issues that were in the way of supporting Emacs 24.4:
- it forces the use of external `openssl` client to workaround the gnutls bug that was fixed in Emacs 24.5
- it adds `cl-generic` backport to provide the missing cl macros
=> More support for emacs 24.4

cask-bootstrap.el
Split old emacs hack
This fixes issue reported at https://github.com/cask/cask/commit/e3b699ab8bb1343e795a6a2077fe7c0a0fd2408f#commitcomment-47101265
=> Split old emacs hack

bin/cask, doc/dev/contributing.rst, doc/guide/installation.rst
Sunset support for Python2 (with half-year extension of time)
Ref: https://devguide.python.org/#status-of-python-branches
closes #498
=> Sunset support for Python2 (just warning)

bin/cask
Fixes issue with environment variables in Windows not supporting bytes
objects for variable keys or values.  An error will occur when running
'cask emacs', this corrects that problem.
=> Fix environment variable values as well.

cask-cli.el, cask.el
Add warning if files directive doesn't match anything.
This feature is suggested at #482.  Thanks, @contrapunctus-1.
=> Add warning if files directive doesn't match anything

cask.el
epl-install-file cannot install depenencies if package-contents are ready.
Need to refresh it first.
=> Add epl-refresh before install.

cask.el
Changing protocol from http to https for security reasons for org source.
Since the Org source  is widely used by the community, we want to make sure that no packages from this source is tampered with.
The Org source supports https: https://orgmode.org/elpa/, and this is the URL that we should all be using instead of the non-https URL.
Here is a good article on this topic as a reference:
https://glyph.twistedmatrix.com/2015/11/editor-malware.html
=> Re #453; Change http -> https org repository

cask.el
Since we are calling `(shut-up-current-output)`, then we must wrap the body forms inside `shut-up`.
=> * cask.el (cask-install): Wrap body inside shut-up

.github/workflows/test.yml
Fixes #539.
I excluded `paths-ignore`, because I think that filter has little impact, because you don't update the documentation as frequently as the code. If you still want them, you could change it as follows, because README is written in Org:
```yaml
paths-ignore:
- '**.md'
- '**.org'
- '**.rst'
```
=> Ensure CI is run when pushing to master

cask.el
[NonGNU ELPA](https://elpa.nongnu.org/) is a new package archive managed by Emacs maintainers that [doesn't require copyright assignment](https://git.savannah.gnu.org/cgit/emacs/nongnu.git/plain/README.org), included by default in Emacs 28.
The Org ELPA is now deprecated in favor of NonGNU:
> Org 9.5 will be the last release to be distributed on Org ELPA.  After
9.5, we won't use Org ELPA for new releases.  Past releases will still
be available, though maybe not indefinitely.
>
> The Org package will continue to be available through GNU ELPA (from
https://elpa.gnu.org/packages/) and a new Org-Contrib package will be
available from https://elpa.nongnu.org/nongnu/.
>
> --- https://list.orgmode.org/87blb3epey.fsf@gnu.org/
=> Add NonGNU ELPA

bin/cask
The fix from #14 got lost when `bin/cask` was first translated to Python and then translated back in d1ee01ba. This puts it back so that Cask works with Nix and other platforms that don't have `bash` even symlinked in `/bin`.
=> Fix shebang

bin/cask
`readlink -f` works on macOS 12, this PR makes Python unnecessary for those systems.
=> Detect functionality, not OS

cask.el
Upstream package-build added this new method which results in an error
when running cask since it's not implemented for package-directory-recipe.
See commit https://github.com/melpa/package-build/commit/f032c806169b0fabbcac1eb44a4f1ae00674bfa8
The timestamp is used for reproducible builds based on commit
timestamp it seems from the upstream code. This is probably not very
useful for cask so just provide the current time here.
=> Add implementation for package-build--get-timestamp

cask.el
Implement the conversion from lisp timestamp to integer manually.
The original patch for this method worked well for emacs 27 and
greater. However time-convert was introduced in emacs 27 so doesn't
work in older versions.
=> Support older emacsen in package-build--get-timestamp

Makefile, README.makefile, README.org
GNU Make will directly invoke simple commands[1], which causes the following error when installing Cask:
make: which: No such file or directory
bin/cask install
make: -c: No such file or directory
make: *** [Makefile:47: /home/wilfred/src/cask/.cask/29.1/elpa] Error 127
This is because `which` is a shell built-in, and there's no guarantee that there's a `which` binary available (e.g. my Arch Linux system doesn't have one).
Use `command -v`, which is more portable, and use shell redirection so Make never attempts to directly invoke it.
[1] https://stackoverflow.com/questions/17547625/how-to-use-shell-builtin-function-from-a-makefile/17550243#17550243
=> Fix Makefile compatibility with recent GNU Make

Makefile
This makes it possible to specify a directory to install into, avoiding the kind of frustration evident in https://github.com/cask/cask/issues/597.
=> Add DESTDIR option
